import SwiftUI

/// Licenses & Sources (§8.3). A DEDICATED screen — EDRDG explicitly requires more
/// than a launch-screen mention for mobile apps. Attribution for every bundled
/// data source is required, not optional.
struct LicensesView: View {
    private struct Source: Identifiable {
        var id: String { name }
        let name: String
        let license: String
        let attribution: String
    }

    private let sources: [Source] = [
        .init(name: "JMdict / EDICT",
              license: "EDRDG Licence (CC BY-SA 4.0 framework)",
              attribution: "Dictionary data is the property of the Electronic Dictionary Research and Development Group (EDRDG) and is used under the Group's licence. See www.edrdg.org."),
        .init(name: "KANJIDIC2",
              license: "EDRDG Licence (CC BY-SA 4.0 framework)",
              attribution: "Kanji data © the Electronic Dictionary Research and Development Group, used under licence."),
        .init(name: "KRADFILE / RADKFILE",
              license: "EDRDG Licence",
              attribution: "Radical decomposition data © EDRDG, used under the Group's licence."),
        .init(name: "Kanjium",
              license: "Open data (see project README)",
              attribution: "Pitch-accent notation and frequency data provided by Uros O. through his free database, with upstream EDRDG attributions."),
        .init(name: "Tatoeba",
              license: "CC BY 2.0 FR",
              attribution: "Example sentences from the Tatoeba Project (tatoeba.org), used under CC-BY."),
        .init(name: "Sudachi / SudachiDict",
              license: "Apache License 2.0",
              attribution: "Morphological analysis by Sudachi, © Works Applications, licensed under Apache-2.0."),
    ]

    var body: some View {
        List {
            Section {
                Text("Kizuna is built on open Japanese-language data. We're grateful to these projects and honor their licences.")
                    .font(.footnote).foregroundStyle(.secondary)
            }
            ForEach(sources) { source in
                Section(source.name) {
                    LabeledContent("Licence", value: source.license)
                    Text(source.attribution).font(.caption).foregroundStyle(.secondary)
                }
            }
            Section("Generated audio") {
                Text("Pronunciation audio is generated by ElevenLabs / OpenAI TTS and cached for replay, used under each provider's output-usage terms (recorded in the project's COMPLIANCE.md).")
                    .font(.caption).foregroundStyle(.secondary)
            }
        }
        .navigationTitle("Licenses & Sources")
    }
}
